import Head from "next/head";
import Navbar from "../components/Navbar/Navbar";
import Video from "../components/Video/Video";
import Content from "../components/Content/Content";
import Footer from "../components/Footer/Footer";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>My Edu Solve</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Video />
      <Content />
      <Footer />
    </div>
  );
}
